import { useEffect } from "react";
import { Link } from "wouter";
import { ArrowLeft } from "lucide-react";
import { Button } from "@/components/ui/button";
import vagabondLogo from "@/assets/vagabond-logo.png";

export default function TermsOfService() {
  useEffect(() => {
    document.title = "Terms of Service | Vagabond Bible";
  }, []);

  return (
    <div className="min-h-screen bg-[hsl(30,20%,97%)]">
      <nav className="bg-white/95 backdrop-blur-sm border-b border-[hsl(30,20%,88%)] sticky top-0 z-50">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between h-16">
            <Link href="/">
              <img src={vagabondLogo} alt="Vagabond Bible" className="h-10" />
            </Link>
            <Link href="/">
              <Button variant="ghost" size="sm" className="text-[hsl(20,10%,40%)]">
                <ArrowLeft className="w-4 h-4 mr-2" />
                Back
              </Button>
            </Link>
          </div>
        </div>
      </nav>

      <main className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <h1 className="text-3xl font-bold text-[hsl(20,10%,20%)] mb-8" data-testid="heading-terms-of-service">
          Terms of Service
        </h1>
        
        <div className="prose prose-lg max-w-none text-[hsl(20,10%,30%)]">
          <p className="text-sm text-[hsl(20,10%,50%)] mb-8">Last updated: January 2025</p>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-[hsl(20,10%,20%)] mb-4">1. Acceptance of Terms</h2>
            <p className="mb-4">
              By accessing or using Vagabond Bible, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our service.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-[hsl(20,10%,20%)] mb-4">2. Description of Service</h2>
            <p className="mb-4">
              Vagabond Bible is a Bible study application that provides access to Scripture, AI-powered study tools, note-taking features, and pastoral chat assistance. The service is available as a web application and mobile app.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-[hsl(20,10%,20%)] mb-4">3. User Accounts</h2>
            <p className="mb-4">
              You must create an account to access certain features. You are responsible for maintaining the confidentiality of your account and for all activities under your account.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-[hsl(20,10%,20%)] mb-4">4. Subscription and Payments</h2>
            <h3 className="text-lg font-medium text-[hsl(20,10%,25%)] mb-2">Free Tier</h3>
            <p className="mb-4">
              Basic features are available for free with usage limits that reset monthly.
            </p>
            <h3 className="text-lg font-medium text-[hsl(20,10%,25%)] mb-2">Pro Subscription</h3>
            <p className="mb-4">
              The Pro subscription costs $9.99 per month and provides unlimited access to all features.
            </p>
            <h3 className="text-lg font-medium text-[hsl(20,10%,25%)] mb-2">Auto-Renewal</h3>
            <p className="mb-4">
              Subscriptions automatically renew unless canceled at least 24 hours before the end of the current period. You can manage or cancel your subscription through your App Store account settings (iOS) or through your account profile (web).
            </p>
            <h3 className="text-lg font-medium text-[hsl(20,10%,25%)] mb-2">Refunds</h3>
            <p className="mb-4">
              For iOS app purchases, refunds are handled by Apple according to their refund policy. For web purchases, please contact us at pastorbrett@thetravelingchurch.com within 7 days of purchase.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-[hsl(20,10%,20%)] mb-4">5. AI Features Disclaimer</h2>
            <p className="mb-4">
              Our AI-powered features, including Pastor Chat, Smart Search, and Verse Insights, are designed to assist with Bible study. The AI responses are generated by artificial intelligence and should not be considered a substitute for professional pastoral counseling, theological education, or personal prayer and discernment.
            </p>
            <p className="mb-4">
              While we strive for accuracy, AI responses may occasionally contain errors or interpretations that differ from your personal beliefs or denominational teachings.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-[hsl(20,10%,20%)] mb-4">6. Acceptable Use</h2>
            <p className="mb-4">You agree not to:</p>
            <ul className="list-disc pl-6 space-y-2 mb-4">
              <li>Use the service for any unlawful purpose</li>
              <li>Attempt to gain unauthorized access to our systems</li>
              <li>Interfere with other users' enjoyment of the service</li>
              <li>Share your account credentials with others</li>
              <li>Use the service to harass, abuse, or harm others</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-[hsl(20,10%,20%)] mb-4">7. Intellectual Property</h2>
            <p className="mb-4">
              The Vagabond Bible app, including its design, features, and content (excluding Bible text), is protected by copyright and other intellectual property laws. Bible translations are used under appropriate licenses.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-[hsl(20,10%,20%)] mb-4">8. User Content</h2>
            <p className="mb-4">
              You retain ownership of any notes or content you create within the app. By using the service, you grant us a license to store and process your content to provide the service.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-[hsl(20,10%,20%)] mb-4">9. Termination</h2>
            <p className="mb-4">
              We may terminate or suspend your account at any time for violations of these terms. You may also request account deletion at any time by contacting us.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-[hsl(20,10%,20%)] mb-4">10. Limitation of Liability</h2>
            <p className="mb-4">
              Vagabond Bible is provided "as is" without warranties of any kind. We are not liable for any indirect, incidental, or consequential damages arising from your use of the service.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-[hsl(20,10%,20%)] mb-4">11. Changes to Terms</h2>
            <p className="mb-4">
              We may modify these terms at any time. Continued use of the service after changes constitutes acceptance of the new terms.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-[hsl(20,10%,20%)] mb-4">12. Contact Us</h2>
            <p className="mb-4">
              If you have any questions about these Terms of Service, please contact us at:
            </p>
            <p className="mb-4">
              <strong>Email:</strong> pastorbrett@thetravelingchurch.com
            </p>
          </section>
        </div>
      </main>

      <footer className="py-8 text-center text-sm text-[hsl(20,10%,40%)] border-t border-[hsl(30,20%,88%)]">
        <p>&copy; {new Date().getFullYear()} Vagabond Bible. All rights reserved.</p>
      </footer>
    </div>
  );
}
