// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/denomination-selector/DenomCards.tsx": () => import("../components/mockups/denomination-selector/DenomCards.tsx"),
  "./components/mockups/denomination-selector/DenomIcons.tsx": () => import("../components/mockups/denomination-selector/DenomIcons.tsx"),
  "./components/mockups/denomination-selector/DenomStepFlow.tsx": () => import("../components/mockups/denomination-selector/DenomStepFlow.tsx")
};
