-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgNkP4Y9LX/hj0Lcsd
a3nSFkfvUHhaGNscG9MkTuGbmxGgCgYIKoZIzj0DAQehRANCAASDMv5uDE4h/FI+
Rw9y1rOxIDrERb82wJYM48zUcSwwNT9KaMa/w+YdbTKSN2RT4E60uCS/oawAhEMg
USvIYFrI
-----END PRIVATE KEY-----